version = 1

test_patterns = ["/src/components/*/*/*.test.tsx"]

exclude_patterns = [
  "src/reportWebVitals.ts",
  "src/setupTests.ts",
  "coverage/**",
  "src/components/*/*.spec.tsx",
  "src/react-app-env.d.ts",
  "src/index.tsx"
]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[transformers]]
name = "prettier"
enabled = true