version = 1

test_patterns = ["/src/components/*/*/*.test.tsx"]

exclude_patterns = [
  "/src/reportWebVitals.ts",
  "/src/setupTests.ts",
  "**/node_modules/**",
  "**/*.spec.ts",
  "**/*.stories.tsx",
  "/coverage/**",
  "**/src/react-app-env.d.ts",
  "/src/index.tsx"
]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[transformers]]
name = "prettier"
enabled = true